-- SPDX-License-Identifier: GPL-3.0-or-later
-- Writable-firmware fix contributed by InsaneFriend (GitHub: saneFriend).
-- Generated by tools/generate_nitro_firmware_vhdl.py -- do not edit.
-- Writable SPI store: header and AP/user regions only; gaps read erased flash.
-- Explicit byte-enabled M10K avoids the inferred partial-word register-file
-- pattern and packs all 2048 served bytes into one 512x32 logical RAM.
-- Generated initialization is synthetic melonDS firmware, not a console dump.
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
library altera_mf;
use altera_mf.altera_mf_components.all;

entity nds_nitro_firmware is
   port
   (
      clk      : in  std_logic;
      -- Zero-based vectors on purpose: nds_nitro_console_wrap converts
      -- the SPI's unsigned(17 downto 2) before it crosses into the
      -- SystemVerilog island, and this sits on that side of the seam.
      fw_addr  : in  std_logic_vector(15 downto 0);
      fw_req   : in  std_logic;
      fw_done  : out std_logic;
      fw_data  : out std_logic_vector(31 downto 0);
      fw_wr    : in  std_logic;
      fw_wlane : in  std_logic_vector(1 downto 0);
      fw_wdata : in  std_logic_vector(7 downto 0);
      -- Held-console configuration only; accepted at edge N, written N+1.
      -- Guest request/write pipelines must be empty before cfg_we.
      cfg_we   : in  std_logic := '0';
      cfg_addr : in  std_logic_vector(6 downto 0) := (others => '0');
      cfg_data : in  std_logic_vector(31 downto 0) := (others => '0');
      cfg_be   : in  std_logic_vector(3 downto 0) := (others => '0')
   );
end entity;

architecture rtl of nds_nitro_firmware is
   signal index : integer range 0 to 511 := 0;
   signal hit, read_hit : std_logic := '0';
   signal req_d1, wr_d1, cfg_d1 : std_logic := '0';
   signal cfg_data_d1 : std_logic_vector(31 downto 0) := (others => '0');
   signal cfg_be_d1 : std_logic_vector(3 downto 0) := (others => '0');
   signal write_data, ram_q : std_logic_vector(31 downto 0);
   signal write_be : std_logic_vector(3 downto 0);
   signal write_enable : std_logic;
begin
   -- Keep the original N+1 commit: guest byte/lane are live on that edge;
   -- configuration data/mask are captured at N. No reset clears this RAM.
   write_data <= cfg_data_d1 when cfg_d1 = '1' else
                 fw_wdata & fw_wdata & fw_wdata & fw_wdata;
   write_be <= cfg_be_d1 when cfg_d1 = '1' else
               std_logic_vector(shift_left(to_unsigned(1, 4), to_integer(unsigned(fw_wlane))))
               when wr_d1 = '1' and hit = '1' else (others => '0');
   write_enable <= '1' when write_be /= "0000" else '0';
   -- The primitive's synchronous read replaces the old array output register.
   -- index/hit still decode at N; data/done emerge at N+1. OLD_DATA returns
   -- the entire pre-write word on a collision, including enabled byte lanes.
   fw_data <= ram_q when read_hit = '1' else (others => '1');
   iram : altsyncram
   generic map (
      operation_mode => "DUAL_PORT",
      intended_device_family => "Cyclone V", ram_block_type => "M10K",
      init_file => "../../rtl/nds_nitro_firmware.mif",
      power_up_uninitialized => "FALSE", lpm_type => "altsyncram",
      numwords_a => 512, numwords_b => 512,
      widthad_a => 9, widthad_b => 9, width_a => 32, width_b => 32,
      width_byteena_a => 4, byte_size => 8,
      clock_enable_input_a => "BYPASS", clock_enable_input_b => "BYPASS",
      clock_enable_output_b => "BYPASS", address_reg_b => "CLOCK0",
      outdata_reg_b => "UNREGISTERED",
      read_during_write_mode_mixed_ports => "OLD_DATA"
   )
   port map (
      clock0 => clk, address_a => std_logic_vector(to_unsigned(index, 9)),
      data_a => write_data, byteena_a => write_be, wren_a => write_enable,
      address_b => std_logic_vector(to_unsigned(index, 9)), q_b => ram_q
   );

   process (clk)
   begin
      if rising_edge(clk) then
         -- Index is a pure address slice; see the region note above.
         cfg_d1 <= cfg_we;
         if cfg_we = '1' then
            index <= to_integer(unsigned'("11") & unsigned(cfg_addr)); -- slots 384..511 only
            hit <= '1';
            cfg_data_d1 <= cfg_data;
            cfg_be_d1 <= cfg_be;
         else
         index <= to_integer(unsigned(fw_addr(8 downto 0)));
         if fw_addr(15 downto 7) = "000000000" then
            hit <= '1';   -- header block, words 0..127
         elsif fw_addr(15 downto 9) = "0111111" and
               fw_addr(8 downto 7) /= "00" then
            hit <= '1';   -- AP configs + user settings, words 32384..32767
         else
            hit <= '0';
         end if;
         end if;
         req_d1  <= fw_req;
         fw_done <= req_d1;
         read_hit <= hit;
         -- 0x0A drives fw_addr exactly like a read, so one cycle later
         -- index/hit already describe the write target. hit also gates
         -- the write, so an address outside the served regions is
         -- silently dropped rather than aliasing onto stored data.
         wr_d1 <= fw_wr;
         -- synthesis translate_off
         assert not ((cfg_we = '1' or cfg_d1 = '1') and
                         (fw_req = '1' or req_d1 = '1' or fw_wr = '1' or wr_d1 = '1'))
            report "configuration overlaps guest firmware transaction" severity failure;
         -- synthesis translate_on
      end if;
   end process;
end architecture;
