#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate standalone option rows from the matching FPGA CONF_STR."""
from pathlib import Path
import json, re
root = Path(__file__).resolve().parents[2]
text = (root / "fpga/mister_nitro_console_island/NDS4MiSTer.sv").read_text()
conf = text.split("localparam CONF_STR={", 1)[1].split("};", 1)[0]
options = []
load = None
for row in re.findall(r'"([^"\n]+)"', conf):
    match = re.fullmatch(r"O\[(\d+)(?::(\d+))?\],([^;]+);", row)
    if match:
        hi, lo = int(match[1]), int(match[2] or match[1])
        parts = match[3].split(",")
        assert 0 <= lo <= hi < 16 and 1 < len(parts[1:]) <= 1 << (hi - lo + 1)
        options.append((lo, hi - lo + 1, parts[0], parts[1:]))
    if row.startswith("FS3,"):
        load = row.split(",")[2]
assert load and options and len(options) < 10
# The standalone browser uses a file-pattern label; the accepted FPGA keeps
# its legacy MiSTer FS3 label. This changes no option bits or generated rows.
load = "Load *.NDS"
version = (Path(__file__).resolve().parent / 'VERSION').read_text().strip()
assert re.fullmatch(r'v\d+\.\d+\.\d+(?:-[A-Za-z0-9.-]+)?', version), \
    'Standalone VERSION must identify its release'
lines = ["// Generated by generate_menu.py from this build's CONF_STR.",
         "#pragma once", '#include <array>', '#include <cstdint>',
         "struct CoreOption { unsigned shift, width, count; const char *label; std::array<const char *, 4> values; };",
         "inline constexpr const char *LOAD_LABEL = " + json.dumps(load) + ";",
         "inline constexpr unsigned LOAD_RECENT_INDEX = 3; // FS3 in CONF_STR",
         "inline constexpr const char *CORE_VERSION = " + json.dumps('NDS4MiSTer ' + version) + ";",
         "inline constexpr std::array<CoreOption, %d> CORE_OPTIONS{{" % len(options)]
for lo, width, label, values in options:
    lines.append("  {%d, %d, %d, %s, {%s}}," % (lo, width, len(values), json.dumps(label), ", ".join(map(json.dumps, values))))
lines += ["}};", "inline constexpr uint16_t CORE_OPTION_MASK = " + str(sum(((1 << width) - 1) << lo for lo, width, *_ in options)) + ";", ""]
(root / "tools/standalone_host/core_menu.h").write_text("\n".join(lines))
