#!/usr/bin/env python3
"""Generate host restore assets from the audited redistributable FreeBIOS."""
from pathlib import Path
import hashlib
from extract_melonds_freebios import HEADER_SHA256, LICENSE_SHA256, IMAGES, extract_array

root = Path(__file__).resolve().parents[1]
header = (root / 'third_party/melonDS/src/FreeBIOS_Data.h').read_bytes()
license_data = (root / 'third_party/melonDS/freebios/drastic_bios_readme.txt').read_bytes()
assert hashlib.sha256(header).hexdigest() == HEADER_SHA256
assert hashlib.sha256(license_data).hexdigest() == LICENSE_SHA256
lines = ['// SPDX-License-Identifier: BSD-2-Clause',
         '// Generated by tools/generate_standalone_freebios.py; no console dumps.',
         '// Copyright (c) 2013 Gilead Kutnick. All rights reserved.',
         '// Full license: third_party/melonDS/freebios/drastic_bios_readme.txt.',
         '#pragma once', '#include <array>', '#include <cstdint>',
         'namespace nds_firmware {']
for array, _, raw_size, size, expected in IMAGES:
    raw = extract_array(header.decode('ascii'), array)
    assert len(raw) == raw_size
    data = raw + bytes(size - len(raw))
    assert hashlib.sha256(data).hexdigest() == expected
    suffix = '7' if 'arm7' in array else '9'
    lines.append(f'inline constexpr std::array<uint8_t, {size}> freebios{suffix}{{{{')
    # C++ zero-initializes the padding; only the audited array is emitted.
    for i in range(0, len(raw), 16):
        lines.append('  ' + ','.join(f'0x{x:02x}' for x in raw[i:i+16]) + ',')
    lines.append('}};')
lines += ['}', '']
(root / 'tools/standalone_host/freebios_media.h').write_text('\n'.join(lines))
