#!/usr/bin/env python3
"""Generate the writable SPI firmware store served to nds_nitro_spi's fw_* port.

Writable-firmware fix contributed by InsaneFriend (GitHub: saneFriend).

Why this exists
---------------
rtl/nds_nitro_console_island.sv used to acknowledge every firmware image fetch
with a zero word, so the ARM7 saw an all-zero flash. Measured against melonDS
with the same stub applied, that is exactly what stops Pokemon Pearl: with the
flash zeroed Pearl renders one flat colour forever, while New Super Mario Bros.
is completely unaffected -- the same split seen on hardware.

Pearl reads 7 of the 512 flash pages; NSMB reads 4. The union is two small
regions, so the core does not need the whole 128 KB image:

    0x00000..0x001FF   header block (points at everything else)
    0x1FA00..0x1FFFF   wifi AP configs + user settings, all CRC16 protected

Serving only those two regions is enough -- 2 KB of block RAM instead of 128 KB,
and block RAM is the resource this design has spare (it is at 98% ALMs).

🚨 SERVING THE DATA IS NOT SUFFICIENT. The store must also be WRITABLE.
Pearl issues 0x06 / 0x0A / 0x04 (write enable, page program, write disable) and
will not boot unless those writes persist. Measured in the oracle:

    full image, writes allowed   -> boots
    2 KB region, writes allowed  -> boots
    full image, writes IGNORED   -> hangs, same ARM9 spin loop as hardware
    NSMB, writes ignored         -> boots (it never writes)

A read-only ROM therefore fails identically to the original zero stub, which is
why the first attempt changed nothing on hardware. Hence four byte-wide RAMs
with initial contents rather than a ROM.

The image is the one melonDS *generates* (melonDS::Firmware(0), default MAC
00:09:BF:11:22:33). It is synthesised data, not a console dump.

Usage:  generate_nitro_firmware_vhdl.py <firmware.bin>
"""

from __future__ import annotations

import hashlib
import pathlib
import sys

# Byte ranges the guest actually fetches, measured with the melonDS probe.
REGIONS = (
    (0x00000, 0x00200),
    (0x1FA00, 0x20000),
)
IMAGE_SIZE = 0x20000  # 128 KB, matching the header the guest follows
# Exact melonDS::Firmware(0) image generated by the vendored melonDS revision.
# Refuse arbitrary 128 KiB inputs: otherwise a maintainer could accidentally
# encode a personal console dump (MAC address, nickname, Wi-Fi settings, etc.)
# into public VHDL while still passing the size check.
EXPECTED_SYNTHETIC_SHA256 = (
    "0e90daacb49fd05bd57f958f7bd98e44da21c707254c8b4d6d09ff76c4337670"
)


def render(image: bytes) -> str:
    # The two served regions have DISJOINT low-9 address bits:
    #   0x00000..0x001FF -> words 0..127     -> low9 0..127
    #   0x1FA00..0x1FFFF -> words 32384..32767 -> low9 128..511
    # so the store index is simply fw_addr(8 downto 0) -- no adders, no
    # subtractors, no mux. On this 98%-full device that arithmetic was the
    # difference between routing and not.
    lanes: list[dict[int, int]] = [{}, {}, {}, {}]
    for start, end in REGIONS:
        for offset in range(start, end, 4):
            slot = (offset // 4) & 0x1FF
            for lane in range(4):
                value = image[offset + lane]
                if value:
                    lanes[lane][slot] = value
    depth = 512

    lines = [
        "-- SPDX-License-Identifier: GPL-3.0-or-later",
        "-- Writable-firmware fix contributed by InsaneFriend (GitHub: saneFriend).",
        "-- Generated by tools/generate_nitro_firmware_vhdl.py -- do not edit.",
        "--",
        "-- Writable SPI firmware store for nds_nitro_spi's fw_* port. Only the",
        "-- regions real games fetch are held; everything else reads all-ones",
        "-- (erased flash) and ignores writes.",
        "--",
        "-- It is a RAM, not a ROM, on purpose: Pokemon Pearl page-programs the",
        "-- flash (0x06/0x0A/0x04) during boot and hangs if those writes are",
        "-- discarded -- indistinguishably from the zero stub this replaced.",
        "--",
        "-- Four byte-wide arrays, NOT one word-wide array with per-lane partial",
        "-- assignment: Quartus 17.0 does not infer byte enables from that VHDL",
        "-- pattern and instead built a 16 Kbit register file, taking the design",
        "-- to 119% ALMs with zero RAM blocks.",
        "--",
        "-- Source image is generated by melonDS (melonDS::Firmware(0)), not a",
        "-- console dump.",
        "library IEEE;",
        "use IEEE.std_logic_1164.all;",
        "use IEEE.numeric_std.all;",
        "",
        "entity nds_nitro_firmware is",
        "   port",
        "   (",
        "      clk      : in  std_logic;",
        "      -- Zero-based vectors on purpose: nds_nitro_console_wrap converts",
        "      -- the SPI's unsigned(17 downto 2) before it crosses into the",
        "      -- SystemVerilog island, and this sits on that side of the seam.",
        "      fw_addr  : in  std_logic_vector(15 downto 0);",
        "      fw_req   : in  std_logic;",
        "      fw_done  : out std_logic;",
        "      fw_data  : out std_logic_vector(31 downto 0);",
        "      fw_wr    : in  std_logic;",
        "      fw_wlane : in  std_logic_vector(1 downto 0);",
        "      fw_wdata : in  std_logic_vector(7 downto 0)",
        "   );",
        "end entity;",
        "",
        "architecture rtl of nds_nitro_firmware is",
        f"   type t_lane is array (0 to {depth - 1}) of std_logic_vector(7 downto 0);",
    ]
    for lane in range(4):
        lines.append(f"   signal LANE{lane} : t_lane := (")
        for slot in sorted(lanes[lane]):
            lines.append(f'      {slot} => x"{lanes[lane][slot]:02X}",')
        # Zero, NOT all-ones: an omitted entry is a genuine 0x00 byte of the
        # image. Erased-flash all-ones belongs only on the unserved-address
        # path below, where hit = '0'.
        lines.append("      others => (others => '0')")
        lines.append("   );")
    lines.extend([
        "   signal index  : integer range 0 to t_lane'high := 0;",
        "   signal hit    : std_logic := '0';",
        "   -- index/hit are registered, so the array read is only correct one",
        "   -- cycle after the address is decoded. fw_done therefore trails",
        "   -- fw_req by two cycles: asserting it sooner hands nds_nitro_spi the",
        "   -- PREVIOUS word. The port permits any latency, so trailing is free.",
        "   signal req_d1 : std_logic := '0';",
        "   -- The write reuses the READ decode one cycle later: nds_nitro_spi",
        "   -- drives fw_addr for 0x0A too, so index/hit are already correct by",
        "   -- then. A separate write decode cost ~163 ALMs and would not route.",
        "   signal wr_d1  : std_logic := '0';",
        "begin",
        "",
        "   process (clk)",
        "   begin",
        "      if rising_edge(clk) then",
        "         -- Index is a pure address slice; see the region note above.",
        "         index <= to_integer(unsigned(fw_addr(8 downto 0)));",
        "         if fw_addr(15 downto 7) = \"000000000\" then",
        "            hit <= '1';   -- header block, words 0..127",
        "         elsif fw_addr(15 downto 9) = \"0111111\" and",
        "               fw_addr(8 downto 7) /= \"00\" then",
        "            hit <= '1';   -- AP configs + user settings, words 32384..32767",
        "         else",
        "            hit <= '0';",
        "         end if;",
        "         req_d1  <= fw_req;",
        "         fw_done <= req_d1;",
        "         if hit = '1' then",
        "            fw_data <= LANE3(index) & LANE2(index) &",
        "                       LANE1(index) & LANE0(index);",
        "         else",
        "            fw_data <= (others => '1');",
        "         end if;",
        "         -- 0x0A drives fw_addr exactly like a read, so one cycle later",
        "         -- index/hit already describe the write target. hit also gates",
        "         -- the write, so an address outside the served regions is",
        "         -- silently dropped rather than aliasing onto stored data.",
        "         wr_d1 <= fw_wr;",
        "         if wr_d1 = '1' and hit = '1' then",
        "            case fw_wlane is",
        "               when \"00\"   => LANE0(index) <= fw_wdata;",
        "               when \"01\"   => LANE1(index) <= fw_wdata;",
        "               when \"10\"   => LANE2(index) <= fw_wdata;",
        "               when others => LANE3(index) <= fw_wdata;",
        "            end case;",
        "         end if;",
        "      end if;",
        "   end process;",
        "end architecture;",
        "",
    ])
    return "\n".join(lines)

def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    image = pathlib.Path(sys.argv[1]).read_bytes()
    if len(image) != IMAGE_SIZE:
        raise SystemExit(
            f"expected a {IMAGE_SIZE}-byte firmware image, got {len(image)}")
    digest = hashlib.sha256(image).hexdigest()
    if digest != EXPECTED_SYNTHETIC_SHA256:
        raise SystemExit(
            "refusing firmware input that is not the pinned synthetic "
            f"melonDS Firmware(0) image (sha256 {digest})")
    print("source sha256:", digest)

    repo = pathlib.Path(__file__).resolve().parents[1]
    output = repo / "rtl" / "nds_nitro_firmware.vhd"
    output.write_text(render(image), encoding="ascii")
    stored = sum(end - start for start, end in REGIONS)
    print(f"{output}  ({stored} bytes stored of {IMAGE_SIZE})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
