#!/usr/bin/env python3
"""Generate the writable SPI firmware store served to nds_nitro_spi's fw_* port.

Writable-firmware fix contributed by InsaneFriend (GitHub: saneFriend).

Why this exists
---------------
rtl/nds_nitro_console_island.sv used to acknowledge every firmware image fetch
with a zero word, so the ARM7 saw an all-zero flash. Measured against melonDS
with the same stub applied, that is exactly what stops Pokemon Pearl: with the
flash zeroed Pearl renders one flat colour forever, while New Super Mario Bros.
is completely unaffected -- the same split seen on hardware.

Pearl reads 7 of the 512 flash pages; NSMB reads 4. The union is two small
regions, so the core does not need the whole 128 KB image:

    0x00000..0x001FF   header block (points at everything else)
    0x1FA00..0x1FFFF   wifi AP configs + user settings, all CRC16 protected

Serving only those two regions is enough -- 2 KB of block RAM instead of 128 KB,
and block RAM is the resource this design has spare (it is at 98% ALMs).

🚨 SERVING THE DATA IS NOT SUFFICIENT. The store must also be WRITABLE.
Pearl issues 0x06 / 0x0A / 0x04 (write enable, page program, write disable) and
will not boot unless those writes persist. Measured in the oracle:

    full image, writes allowed   -> boots
    2 KB region, writes allowed  -> boots
    full image, writes IGNORED   -> hangs, same ARM9 spin loop as hardware
    NSMB, writes ignored         -> boots (it never writes)

A read-only ROM therefore fails identically to the original zero stub, which is
why the first attempt changed nothing on hardware. Hence writable byte-enabled RAM
with initial contents rather than a ROM.

The image is the one melonDS *generates* (melonDS::Firmware(0), default MAC
00:09:BF:11:22:33). It is synthesised data, not a console dump.

Usage:  generate_nitro_firmware_vhdl.py <firmware.bin>
"""

from __future__ import annotations

import hashlib
import pathlib
import re
import sys

# Byte ranges the guest actually fetches, measured with the melonDS probe.
REGIONS = (
    (0x00000, 0x00200),
    (0x1FA00, 0x20000),
)
IMAGE_SIZE = 0x20000  # 128 KB, matching the header the guest follows
# Exact melonDS::Firmware(0) image generated by the vendored melonDS revision.
# Refuse arbitrary 128 KiB inputs: otherwise a maintainer could accidentally
# encode a personal console dump (MAC address, nickname, Wi-Fi settings, etc.)
# into public VHDL while still passing the size check.
EXPECTED_SYNTHETIC_SHA256 = (
    "0e90daacb49fd05bd57f958f7bd98e44da21c707254c8b4d6d09ff76c4337670"
)

# Firmware(0) constructs a valid synthetic image, then FirmwareMem::Reset()
# applies the touchscreen calibration below to BOTH redundant user-setting
# copies and updates their CRCs before either direct boot or SPI firmware reads
# can observe them. Encoding the pre-Reset image leaves a valid-CRC but
# zero-span calibration in SPI flash: pen-down still works, while software that
# consumes the flash copy cannot turn raw ADC samples into screen coordinates.
USER_SETTINGS_OFFSETS = (0x1FE00, 0x1FF00)
TOUCH_CALIBRATION_OFFSET = 0x58
TOUCH_CALIBRATION = bytes((
    0x00, 0x00,  # ADC1 X = 0
    0x00, 0x00,  # ADC1 Y = 0
    0x00, 0x00,  # Pixel1 = (0, 0)
    0xF0, 0x0F,  # ADC2 X = 255 << 4
    0xF0, 0x0B,  # ADC2 Y = 191 << 4
    0xFF, 0xBF,  # Pixel2 = (255, 191)
))


def crc16(data: bytes | bytearray, start: int) -> int:
    """Match melonDS CRC16() / DS firmware's reflected 0xA001 CRC."""
    value = start
    for byte in data:
        value ^= byte
        for _ in range(8):
            value = (value >> 1) ^ (0xA001 if value & 1 else 0)
    return value & 0xFFFF


DEFAULT_NICKNAME = "MiSTer"


def apply_melonds_runtime_defaults(source: bytes) -> bytes:
    """Apply melonDS virtual-touch calibration, then the project default name."""
    image = bytearray(source)
    for base in USER_SETTINGS_OFFSETS:
        start = base + TOUCH_CALIBRATION_OFFSET
        image[start:start + len(TOUCH_CALIBRATION)] = TOUCH_CALIBRATION
        # Project-local default only; never change vendored melonDS defaults.
        nickname = DEFAULT_NICKNAME.encode("utf-16le")
        image[base + 0x06:base + 0x1A] = nickname.ljust(20, b"\0")
        image[base + 0x1A:base + 0x1C] = (len(nickname) // 2).to_bytes(2, "little")
        checksum = crc16(image[base:base + 0x70], 0xFFFF)
        image[base + 0x72] = checksum & 0xFF
        image[base + 0x73] = checksum >> 8
    return bytes(image)


def packed_words(image: bytes) -> list[int]:
    # Disjoint low-nine word indices: header 0..127, AP/user 128..511.
    words = [0] * 512
    for start, end in REGIONS:
        for offset in range(start, end, 4):
            words[(offset // 4) & 0x1FF] = int.from_bytes(image[offset:offset + 4], "little")
    return words


def render_mif(image: bytes) -> str:
    lines = ["-- Generated synthetic SPI firmware; see generate_nitro_firmware_vhdl.py.",
             "WIDTH=32;", "DEPTH=512;", "ADDRESS_RADIX=HEX;", "DATA_RADIX=HEX;", "CONTENT BEGIN"]
    lines += [f"{i:03X} : {word:08X};" for i, word in enumerate(packed_words(image))]
    return "\n".join(lines + ["END;", ""])


def render(image: bytes) -> str:
    # Bytes are emitted separately to the MIF; ports and pipeline are invariant.
    return r'''-- SPDX-License-Identifier: GPL-3.0-or-later
-- Writable-firmware fix contributed by InsaneFriend (GitHub: saneFriend).
-- Generated by tools/generate_nitro_firmware_vhdl.py -- do not edit.
-- Writable SPI store: header and AP/user regions only; gaps read erased flash.
-- Explicit byte-enabled M10K avoids the inferred partial-word register-file
-- pattern and packs all 2048 served bytes into one 512x32 logical RAM.
-- Generated initialization is synthetic melonDS firmware, not a console dump.
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
library altera_mf;
use altera_mf.altera_mf_components.all;

entity nds_nitro_firmware is
   port
   (
      clk      : in  std_logic;
      -- Zero-based vectors on purpose: nds_nitro_console_wrap converts
      -- the SPI's unsigned(17 downto 2) before it crosses into the
      -- SystemVerilog island, and this sits on that side of the seam.
      fw_addr  : in  std_logic_vector(15 downto 0);
      fw_req   : in  std_logic;
      fw_done  : out std_logic;
      fw_data  : out std_logic_vector(31 downto 0);
      fw_wr    : in  std_logic;
      fw_wlane : in  std_logic_vector(1 downto 0);
      fw_wdata : in  std_logic_vector(7 downto 0);
      -- Held-console configuration only; accepted at edge N, written N+1.
      -- Guest request/write pipelines must be empty before cfg_we.
      cfg_we   : in  std_logic := '0';
      cfg_addr : in  std_logic_vector(6 downto 0) := (others => '0');
      cfg_data : in  std_logic_vector(31 downto 0) := (others => '0');
      cfg_be   : in  std_logic_vector(3 downto 0) := (others => '0')
   );
end entity;

architecture rtl of nds_nitro_firmware is
   signal index : integer range 0 to 511 := 0;
   signal hit, read_hit : std_logic := '0';
   signal req_d1, wr_d1, cfg_d1 : std_logic := '0';
   signal cfg_data_d1 : std_logic_vector(31 downto 0) := (others => '0');
   signal cfg_be_d1 : std_logic_vector(3 downto 0) := (others => '0');
   signal write_data, ram_q : std_logic_vector(31 downto 0);
   signal write_be : std_logic_vector(3 downto 0);
   signal write_enable : std_logic;
begin
   -- Keep the original N+1 commit: guest byte/lane are live on that edge;
   -- configuration data/mask are captured at N. No reset clears this RAM.
   write_data <= cfg_data_d1 when cfg_d1 = '1' else
                 fw_wdata & fw_wdata & fw_wdata & fw_wdata;
   write_be <= cfg_be_d1 when cfg_d1 = '1' else
               std_logic_vector(shift_left(to_unsigned(1, 4), to_integer(unsigned(fw_wlane))))
               when wr_d1 = '1' and hit = '1' else (others => '0');
   write_enable <= '1' when write_be /= "0000" else '0';
   -- The primitive's synchronous read replaces the old array output register.
   -- index/hit still decode at N; data/done emerge at N+1. OLD_DATA returns
   -- the entire pre-write word on a collision, including enabled byte lanes.
   fw_data <= ram_q when read_hit = '1' else (others => '1');
   iram : altsyncram
   generic map (
      operation_mode => "DUAL_PORT",
      intended_device_family => "Cyclone V", ram_block_type => "M10K",
      init_file => "../../rtl/nds_nitro_firmware.mif",
      power_up_uninitialized => "FALSE", lpm_type => "altsyncram",
      numwords_a => 512, numwords_b => 512,
      widthad_a => 9, widthad_b => 9, width_a => 32, width_b => 32,
      width_byteena_a => 4, byte_size => 8,
      clock_enable_input_a => "BYPASS", clock_enable_input_b => "BYPASS",
      clock_enable_output_b => "BYPASS", address_reg_b => "CLOCK0",
      outdata_reg_b => "UNREGISTERED",
      read_during_write_mode_mixed_ports => "OLD_DATA"
   )
   port map (
      clock0 => clk, address_a => std_logic_vector(to_unsigned(index, 9)),
      data_a => write_data, byteena_a => write_be, wren_a => write_enable,
      address_b => std_logic_vector(to_unsigned(index, 9)), q_b => ram_q
   );

   process (clk)
   begin
      if rising_edge(clk) then
         -- Index is a pure address slice; see the region note above.
         cfg_d1 <= cfg_we;
         if cfg_we = '1' then
            index <= to_integer(unsigned'("11") & unsigned(cfg_addr)); -- slots 384..511 only
            hit <= '1';
            cfg_data_d1 <= cfg_data;
            cfg_be_d1 <= cfg_be;
         else
         index <= to_integer(unsigned(fw_addr(8 downto 0)));
         if fw_addr(15 downto 7) = "000000000" then
            hit <= '1';   -- header block, words 0..127
         elsif fw_addr(15 downto 9) = "0111111" and
               fw_addr(8 downto 7) /= "00" then
            hit <= '1';   -- AP configs + user settings, words 32384..32767
         else
            hit <= '0';
         end if;
         end if;
         req_d1  <= fw_req;
         fw_done <= req_d1;
         read_hit <= hit;
         -- 0x0A drives fw_addr exactly like a read, so one cycle later
         -- index/hit already describe the write target. hit also gates
         -- the write, so an address outside the served regions is
         -- silently dropped rather than aliasing onto stored data.
         wr_d1 <= fw_wr;
         -- synthesis translate_off
         assert not ((cfg_we = '1' or cfg_d1 = '1') and
                         (fw_req = '1' or req_d1 = '1' or fw_wr = '1' or wr_d1 = '1'))
            report "configuration overlaps guest firmware transaction" severity failure;
         -- synthesis translate_on
      end if;
   end process;
end architecture;
'''

def render_profile_header(image: bytes) -> str:
    pages = b"".join(image[base:base + 0x100] for base in USER_SETTINGS_OFFSETS)
    offset = int.from_bytes(image[0x20:0x22], "little") * 8
    checksums = int.from_bytes(image[0x26:0x28], "little") | (int.from_bytes(image[4:6], "little") << 16)
    lines = ["// SPDX-License-Identifier: GPL-3.0-or-later",
             "// Generated by tools/generate_nitro_firmware_vhdl.py from pinned synthetic melonDS firmware.",
             "// Copyright 2016-2026 melonDS team; project-specific MiSTer default and virtual touch calibration.",
             "// This is generated data, not a console dump. Do not edit.",
             "#pragma once", "#include <array>", "#include <cstdint>", "namespace nds_firmware {"]
    for name, data in (("builtin_user_pages", pages), ("builtin_profile", pages[:0x70])):
        lines.append(f"inline constexpr std::array<uint8_t, {len(data)}> {name}{{{{")
        for i in range(0, len(data), 16):
            lines.append("  " + ",".join(f"0x{x:02x}" for x in data[i:i+16]) + ",")
        lines.append("}};")
    lines += [f"inline constexpr uint32_t builtin_user_offset = 0x{offset:08x};",
              f"inline constexpr uint32_t builtin_checksums = 0x{checksums:08x};", "}", ""]
    return "\n".join(lines)


def update_loader_defaults(text: str, image: bytes) -> str:
    words = [int.from_bytes(image[0x1FE00 + i:0x1FE04 + i], "little") for i in range(0, 0x70, 4)]
    lines = ["   -- BEGIN GENERATED BUILTIN PROFILE (generate_nitro_firmware_vhdl.py)",
             "   type t_builtin_profile is array (0 to 27) of std_logic_vector(31 downto 0);",
             "   constant BUILTIN_USER_WORDS : t_builtin_profile := ("]
    lines += [f'      {i} => x"{word:08X}",' for i, word in enumerate(words) if word]
    lines += ["      others => (others => '0'));", "   -- END GENERATED BUILTIN PROFILE"]
    return re.sub(r"   -- BEGIN GENERATED BUILTIN PROFILE.*?   -- END GENERATED BUILTIN PROFILE",
                  "\n".join(lines), text, flags=re.S)


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    image = pathlib.Path(sys.argv[1]).read_bytes()
    if len(image) != IMAGE_SIZE:
        raise SystemExit(
            f"expected a {IMAGE_SIZE}-byte firmware image, got {len(image)}")
    digest = hashlib.sha256(image).hexdigest()
    if digest != EXPECTED_SYNTHETIC_SHA256:
        raise SystemExit(
            "refusing firmware input that is not the pinned synthetic "
            f"melonDS Firmware(0) image (sha256 {digest})")
    print("source sha256:", digest)
    image = apply_melonds_runtime_defaults(image)

    repo = pathlib.Path(__file__).resolve().parents[1]
    output = repo / "rtl" / "nds_nitro_firmware.vhd"
    output.write_text(render(image), encoding="ascii")
    (repo / "rtl/nds_nitro_firmware.mif").write_text(render_mif(image), encoding="ascii")
    (repo / "tools/standalone_host/builtin_firmware_profile.h").write_text(render_profile_header(image), encoding="ascii")
    loader = repo / "third_party/Nitro_DarkSide/d2dabe/rtl/nds_loader.vhd"
    old_loader = loader.read_text()
    if old_loader.count("-- BEGIN GENERATED BUILTIN PROFILE") != 1:
        raise SystemExit("loader missing generated profile marker")
    loader.write_text(update_loader_defaults(old_loader, image))
    stored = sum(end - start for start, end in REGIONS)
    print(f"{output}  ({stored} bytes stored of {IMAGE_SIZE})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
