#!/usr/bin/env python3
"""Generate reloadable BIOS RAMs initialized only from audited public FreeBIOS.

No input-image option is provided: personal BIOS files must be loaded at runtime.
The CPU read still has exactly one clock of latency, including above BIOS9's
4 KiB image. Writes are accepted only while the console reset is asserted.
"""

from __future__ import annotations

import pathlib

from generate_nitro_freebios_vhdl import (
    HEADER_SHA256, IMAGES, array_bytes, padded_words, sha256,
)


def outputs(repo: pathlib.Path) -> dict[pathlib.Path, str]:
    data = (repo / "third_party/melonDS/src/FreeBIOS_Data.h").read_bytes()
    if sha256(data) != HEADER_SHA256:
        raise ValueError("FreeBIOS source does not match audited public image")
    result = {}
    for image in IMAGES:
        words = padded_words(array_bytes(data.decode("ascii"), image.array_name), image)
        bits = (len(words) - 1).bit_length()
        stem = image.stem.replace("freebios", "bootbios")
        notice = (
            "-- SPDX-License-Identifier: BSD-2-Clause\n"
            "-- Generated by tools/generate_nitro_bootbios.py from public melonDS FreeBIOS.\n"
            "-- License: third_party/melonDS/freebios/drastic_bios_readme.txt\n"
        )
        mif = notice + f"DEPTH = {len(words)};\nWIDTH = 32;\nADDRESS_RADIX = HEX;\nDATA_RADIX = HEX;\nCONTENT BEGIN\n"
        mif += "".join(f"   {i:03X} : {w:08X};\n" for i, w in enumerate(words)) + "END;\n"
        result[repo / "rtl" / f"{stem}.mif"] = mif
        initial = "\n".join(f'      {i} => x"{w:08X}",' for i, w in enumerate(words) if w)
        vhdl = notice + f'''library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
library altera_mf;
use altera_mf.altera_mf_components.all;

entity {stem} is
   generic (is_simu : std_logic := '0');
   port (
      clk : in std_logic;
      reset : in std_logic;
      {image.address_name} : in unsigned({image.address_width + 1} downto 2);
      {image.data_name} : out std_logic_vector(31 downto 0);
      load_addr : in unsigned({bits + 1} downto 2);
      load_data : in std_logic_vector(31 downto 0);
      load_be : in std_logic_vector(3 downto 0);
      load_we : in std_logic
   );
end entity;

architecture rtl of {stem} is
   signal q : std_logic_vector(31 downto 0);
   signal valid_q : std_logic := '0';
   signal write_enable : std_logic;
begin
   write_enable <= load_we and reset;
   process(clk)
   begin
      if rising_edge(clk) then
         if {image.address_name} < {len(words)} then valid_q <= '1';
         else valid_q <= '0'; end if;
      end if;
   end process;
   {image.data_name} <= q when valid_q = '1' else (others => '0');

   g_sim : if is_simu = '1' generate
      type t_ram is array(0 to {len(words) - 1}) of std_logic_vector(31 downto 0);
      signal ram : t_ram := (
{initial}
         others => (others => '0')
      );
   begin
      process(clk)
      begin
         if rising_edge(clk) then
            q <= ram(to_integer({image.address_name}({bits + 1} downto 2)));
            if write_enable = '1' then
               for lane in 0 to 3 loop
                  if load_be(lane) = '1' then
                     ram(to_integer(load_addr))(lane*8+7 downto lane*8) <=
                        load_data(lane*8+7 downto lane*8);
                  end if;
               end loop;
            end if;
         end if;
      end process;
   end generate;

   g_m10k : if is_simu = '0' generate
   begin
      iram : altsyncram
      generic map (
         operation_mode => "BIDIR_DUAL_PORT",
         intended_device_family => "Cyclone V",
         ram_block_type => "M10K",
         init_file => "../../rtl/{stem}.mif",
         power_up_uninitialized => "FALSE",
         lpm_type => "altsyncram",
         numwords_a => {len(words)}, numwords_b => {len(words)},
         widthad_a => {bits}, widthad_b => {bits},
         width_a => 32, width_b => 32,
         width_byteena_a => 4, width_byteena_b => 4,
         byte_size => 8,
         address_reg_b => "CLOCK0",
         indata_reg_b => "CLOCK0",
         byteena_reg_b => "CLOCK0",
         wrcontrol_wraddress_reg_b => "CLOCK0",
         clock_enable_input_a => "BYPASS",
         clock_enable_input_b => "BYPASS",
         clock_enable_output_a => "BYPASS",
         clock_enable_output_b => "BYPASS",
         outdata_reg_a => "UNREGISTERED",
         outdata_reg_b => "UNREGISTERED",
         read_during_write_mode_mixed_ports => "DONT_CARE"
      )
      port map (
         clock0 => clk,
         address_a => std_logic_vector({image.address_name}({bits + 1} downto 2)),
         q_a => q, wren_a => '0',
         address_b => std_logic_vector(load_addr),
         data_b => load_data, byteena_b => load_be, wren_b => write_enable
      );
   end generate;
end architecture;
'''
        result[repo / "rtl" / f"{stem}.vhd"] = vhdl
    return result


if __name__ == "__main__":
    for path, content in outputs(pathlib.Path(__file__).resolve().parents[1]).items():
        path.write_text(content, encoding="ascii")
        print(path)
