#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate authored Thumb/STM programs and an independent bus-store oracle.
No ROM data. STM expectations are computed from addressing semantics, not RTL.
"""
from pathlib import Path
import sys
out = Path(sys.argv[1])
out.mkdir(parents=True, exist_ok=True)
program = [0xE321F01F, 0xE3A0A301]  # system mode, r10=0x04000000 result port
expected = []
def emit(*words): program.extend(words)
def load(reg, value): emit(0xE59F0000 | reg << 12, 0xEA000000, value & 0xffffffff)
def store(reg, value9, value7=None):
    emit(0xE58A0000 | reg << 12)
    expected.append((0x04000000, value9 & 0xffffffff, (value9 if value7 is None else value7) & 0xffffffff))
# IA/IB/DA/DB, writeback on/off, base first/middle/last/absent.
for pre in range(2):
 for up in range(2):
  for wb in range(2):
   for regs in ([4,5], [0,4,5], [0,4], [0,5]):
    base = 0x03001080
    values = {0:0x12345678, 4:base, 5:0x87654321}
    for reg,value in values.items(): load(reg,value)
    count=len(regs); end=base+(4*count if up else -4*count)
    addr=base+(4 if pre else 0) if up else base-4*count+(0 if pre else 4)
    emit(0xE8040000 | pre<<24 | up<<23 | wb<<21 | sum(1<<r for r in regs))
    for i,r in enumerate(regs):
     value7=end if r==4 and i>0 and wb else values[r]
     expected.append((addr+4*i,values[r],value7))
    store(4,end if wb else base)
# Every pair of low registers, including aliasing and signed/wrapping inputs.
for op in ('add','cmp'):
 for seed in (0,1):
  values=[(0xFFFFF001+i*0x2345 if seed else 0x1234+i*0x10001)&0xffffffff for i in range(8)]
  for rd in range(8):
   for rs in range(8):
    load(rd,values[rd])
    if rd!=rs: load(rs,values[rs])
    emit(0xE1580008) # cmp r8,r8: seed Z=C=1; ADD must preserve flags.
    thumb=(0x4400 if op=='add' else 0x4500) | rs<<3 | rd
    # lr points after the Thumb pair; r11 points to pair with Thumb bit set.
    emit(0xE28FE008,0xE28FB001,0xE12FFF1B,0x47700000 | thumb)
    a,b=values[rd],values[rs]
    result=(a+b)&0xffffffff if op=='add' else a
    store(rd,result)
    emit(0xE10F9000,0xE209920F) # mrs r9,cpsr; and r9,r9,#0xf0000000
    diff=(a-b)&0xffffffff
    flags=0x60000000 if op=='add' else ((diff>>31)<<31 | int(diff==0)<<30 | int(a>=b)<<29 | int(bool((a^b)&(a^diff)&0x80000000))<<28)
    store(9,flags)
emit(0xEAFFFFFE)
assert len(program)<16384
init='\n'.join(f'    m({i}):=x"{v:08X}";' for i,v in enumerate(program))
def arr(col): return ',\n'.join(f'    x"{r[col]:08X}"' for r in expected)
ports='''clk=>clk,ce=>ce,reset=>reset,dbg_pc=>pc,
      savestate_bus=>ss,ss_wired_done=>open,gb_bus_Adr=>addr,gb_bus_rnw=>rnw,
      gb_bus_ena=>ena,gb_bus_seq=>open,gb_bus_code=>code,gb_bus_acc=>acc,
      gb_bus_dout=>dout,gb_bus_din=>din,gb_bus_done=>done,dma_on=>dma,
      CPU_bus_idle=>open,PC_in_BIOS=>open,cpu_halt=>open,lastread=>open,jump_out=>open,
      IRQ_in=>'0',unhalt=>'0',new_halt=>'0' '''
extra=''',cp15_vector_hi=>open,cp15_pu_enable=>open,
      cp15_icache_ena=>open,cp15_dcache_ena=>open,cp15_itcm_ena=>open,cp15_itcm_load=>open,
      cp15_dtcm_ena=>open,cp15_dtcm_load=>open,cp15_dtcm_base=>open,cp15_dtcm_size=>open,
      cp15_itcm_size=>open,bus_cacheable_i=>open,bus_cacheable_d=>open,cache_op_busy=>'0' '''
tb=f'''-- Generated by tools/test_insanefriend_cpu.py; no game data.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.env.all;
use work.pProc_bus_gba.all;
entity tb_if_cpu is
 generic(CPU9:boolean:=true; READ_DELAY:positive:=1; STEP_PERIOD:positive:=1);
end;
architecture sim of tb_if_cpu is
 signal clk:std_logic:='0'; signal reset:std_logic:='1';
 signal ss:proc_bus_gb_type:=((others=>'0'),(others=>'0'),'0','0',"10","1111",'0');
 signal addr,din,dout,pc:std_logic_vector(31 downto 0);
 signal ena,done,code,rnw,ce,dma:std_logic:='0';
 signal acc:std_logic_vector(1 downto 0);
 signal ticks,results: natural:=0; signal finished:boolean:=false;
 type words is array(natural range <>) of std_logic_vector(31 downto 0);
 constant expected_addr:words:=({arr(0)});
 constant expected9:words:=({arr(1)});
 constant expected7:words:=({arr(2)});
 function init return words is
  variable m:words(0 to 16383):=(others=>x"E7F000F0");
 begin
{init}
 return m;end;
 constant memory:words(0 to 16383):=init;
begin
 clk<=not clk after 5 ns;
 ce<='1' when ticks mod STEP_PERIOD=0 else '0';
 dma<='1' when ticks mod 19<6 else '0';
 process(clk) begin if rising_edge(clk) then ticks<=ticks+1;end if;end process;
 g9:if CPU9 generate
  dut:entity work.nds_cpu9 generic map(is_simu=>'0') port map({ports}{extra});
 end generate;
 g7:if not CPU9 generate
  dut:entity work.gba_cpu generic map(is_simu=>'0') port map({ports});
 end generate;
 process(clk)
  variable pending:boolean:=false;variable remaining:natural:=0;
  variable payload,expected_data:std_logic_vector(31 downto 0);variable requests:natural:=0;
 begin
  if rising_edge(clk) then
   if reset='1' then done<='0';din<=(others=>'0');
   else
    if done='1' and ce='1' then done<='0';end if;
    if pending then
     if remaining=0 then done<='1';din<=payload;pending:=false;
     else remaining:=remaining-1;end if;
    end if;
    if ena='1' then
     assert not pending report "overlapping request" severity failure;
     pending:=true;remaining:=READ_DELAY-1+requests mod STEP_PERIOD;requests:=requests+1;
     payload:=(others=>'0');
     if rnw='1' then
      assert addr(31 downto 16)=x"0200" report "unexpected read " & to_hstring(addr) severity failure;
      payload:=std_logic_vector(rotate_right(unsigned(memory(to_integer(unsigned(addr(15 downto 2))))),to_integer(unsigned(addr(1 downto 0)))*8));
      if acc=ACCESS_16BIT then payload:=x"0000" & payload(15 downto 0);end if;
     else
      assert results<expected_addr'length report "duplicate store" severity failure;
      if CPU9 then expected_data:=expected9(results);else expected_data:=expected7(results);end if;
      assert acc=ACCESS_32BIT and addr=expected_addr(results) and dout=expected_data
       report "store " & integer'image(results) & " addr=" & to_hstring(addr) & " got=" & to_hstring(dout) & " expected=" & to_hstring(expected_data) severity failure;
      results<=results+1;
      if results+1=expected_addr'length then finished<=true;end if;
     end if;
    end if;
   end if;
  end if;
 end process;
 process begin
  wait for 40 ns;ss.Din<=x"02000000";ss.ena<='1';wait for 20 ns;ss.ena<='0';wait for 40 ns;reset<='0';
  wait until finished for 20 ms;
  assert finished report "program timeout PC=" & to_hstring(pc) severity failure;
  report "PASS: Thumb low ADD/CMP and STM matrix CPU9=" & boolean'image(CPU9) & " stores=" & integer'image(results);
  stop;wait;
 end process;
end;
'''
(out/'tb_if_cpu.vhd').write_text(tb)
print(f'Generated {len(program)} authored instruction/data words, {len(expected)} checked stores per CPU')
