#pragma once

#include "melonds/MelonDsBackend.h"
#include "replay/ExternalTimeWindowDdrProducer.h"

#include <cstddef>
#include <cstdint>
#include <functional>
#include <string>
#include <vector>

namespace nds4mister {

// Atomic output of one irreversible emulator scheduler closure. The caller
// must return only the exact IRQ-transition suffix created by that closure;
// the bridge separately requires proof that the backend queue was empty on
// entry so an older, unnamed tail cannot be mixed into this group.
struct ExternalTimeWindowDdrClosureOutput {
    ExternalTimeWindow window{};
    std::vector<ExternalIRQTransition> transitions;
};

using ExternalTimeWindowDdrClosure = std::function<bool(
    ExternalTimeWindowDdrClosureOutput& output, std::string& error)>;

// The requester may observe its returned read value only after the complete
// blocking-MMIO replacement has passed producer validation and its ordinary
// DDR commit is visible.  Carrying all three admission tags prevents a late
// value from completing a different retained request after reset/recovery.
struct ExternalBlockingMMIODdrReadResponse {
    std::uint32_t epoch = 0;
    std::uint32_t sourceSequence = 0;
    std::uint32_t barrierSequence = 0;
    std::uint32_t value = 0;
    bool valid = false;
};

using ExternalBlockingMMIODdrClosure = std::function<bool(
    ExternalBlockingMMIOCompletion& output, std::string& error)>;

// Simulator-only conversion boundary between the melonDS external-time-window
// result and the fixed-slot DDR producer. ExternalTimeWindowDdrProducer owns
// all capacity/session preflight, so close() is never called while the queue is
// full, unacknowledged, inactive, or exhausted. Once close() is entered it is
// irreversible: false, an exception, conversion/allocation failure, a stale
// pre-entry IRQ tail, or producer validation failure poisons the producer and
// cannot be retried until its explicit model-reset recovery contract is met.
//
// queuedTransitionsBeforeClosure is deliberately explicit. Integration must
// sample the backend's pending transition count immediately before this call;
// only zero is accepted. close() must then atomically close one window and
// return exactly the transitions generated by it.
ExternalTimeWindowDdrPublishResult publishExternalTimeWindowDdr(
    ExternalTimeWindowDdrProducer& producer,
    std::size_t queuedTransitionsBeforeClosure,
    const ExternalTimeWindowDdrClosure& close,
    ExternalTimeWindowDdrReceipt& receipt,
    std::string& error) noexcept;

// Atomically joins one already-admitted FPGA blocking request to the melonDS
// transaction/closure and BRRP DDR publication.  The producer performs all
// session, slot, identity, event-capacity, and sequence-space preflight before
// close() can mutate the model. queuedTransitionsBeforeClosure must be the
// backend queue depth sampled immediately before this call and must be zero.
//
// close() is normally a one-line call to
// MelonDsBackend::execute_external_blocking_mmio_transaction(). Its returned
// replacement window must exactly echo the immutable FPGA admission identity.
// That identity also carries the requester CPU and full 64-bit continuation
// frontier into the BRRP sidecar; the initial replacement R may remain below
// that bound because the retained requester is released only by the later
// continuation. Every event is copied without normalization. Any callback,
// echo, conversion, or transport fault poisons the producer and cannot be
// retried until the explicit model-reset recovery contract is met.
// readResponse remains invalid on every result except Published.
ExternalTimeWindowDdrPublishResult publishExternalBlockingMMIODdr(
    ExternalTimeWindowDdrProducer& producer,
    std::size_t queuedTransitionsBeforeClosure,
    const ExternalTimeWindowDdrBarrierIdentity& expected,
    const ExternalBlockingMMIODdrClosure& close,
    ExternalTimeWindowDdrReceipt& receipt,
    ExternalBlockingMMIODdrReadResponse& readResponse,
    std::string& error) noexcept;

} // namespace nds4mister
